// <auto-generated />
using System;
using BackendApi.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250601144324_CreateDatabaseAndTables")]
    partial class CreateDatabaseAndTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Database/Migration")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Database.Entityes.T009PPD", b =>
                {
                    b.Property<long>("UsuNumppd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usu_numppd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UsuNumppd"));

                    b.Property<string>("UsuCiffob")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_ciffob");

                    b.Property<int?>("UsuCodcli")
                        .HasColumnType("int")
                        .HasColumnName("usu_codcli");

                    b.Property<int?>("UsuCodcpg")
                        .HasColumnType("int")
                        .HasColumnName("usu_codcpg");

                    b.Property<string>("UsuCodcrt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_codcrt");

                    b.Property<short>("UsuCodemp")
                        .HasColumnType("smallint")
                        .HasColumnName("usu_codemp");

                    b.Property<short?>("UsuCodfpg")
                        .HasColumnType("smallint")
                        .HasColumnName("usu_codfpg");

                    b.Property<int?>("UsuCodrep")
                        .HasColumnType("int")
                        .HasColumnName("usu_codrep");

                    b.Property<int?>("UsuCodtra")
                        .HasColumnType("int")
                        .HasColumnName("usu_codtra");

                    b.Property<DateTime?>("UsuDatemi")
                        .HasColumnType("datetime2")
                        .HasColumnName("usu_datemi");

                    b.Property<DateTime?>("UsuDatfat")
                        .HasColumnType("datetime2")
                        .HasColumnName("usu_datfat");

                    b.Property<DateTime?>("UsuDatprv")
                        .HasColumnType("datetime2")
                        .HasColumnName("usu_datprv");

                    b.Property<short?>("UsuNatope")
                        .HasColumnType("smallint")
                        .HasColumnName("usu_natope");

                    b.Property<string>("UsuNecage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_necage");

                    b.Property<int?>("UsuNumnf2")
                        .HasColumnType("int")
                        .HasColumnName("usu_numnf2");

                    b.Property<int?>("UsuNumnfv")
                        .HasColumnType("int")
                        .HasColumnName("usu_numnfv");

                    b.Property<int?>("UsuNumpe2")
                        .HasColumnType("int")
                        .HasColumnName("usu_numpe2");

                    b.Property<int?>("UsuNumped")
                        .HasColumnType("int")
                        .HasColumnName("usu_numped");

                    b.Property<string>("UsuObsfin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_obsfin");

                    b.Property<string>("UsuObsped")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_obsped");

                    b.Property<string>("UsuPedcli")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_pedcli");

                    b.Property<short?>("UsuPedime")
                        .HasColumnType("smallint")
                        .HasColumnName("usu_pedime");

                    b.Property<decimal?>("UsuPerdsc")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("usu_perdsc");

                    b.Property<DateTime?>("UsuPrvfat")
                        .HasColumnType("datetime2")
                        .HasColumnName("usu_prvfat");

                    b.Property<string>("UsuRetmer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_retmer");

                    b.Property<short?>("UsuSitppd")
                        .HasColumnType("smallint")
                        .HasColumnName("usu_sitppd");

                    b.Property<short?>("UsuTipdis")
                        .HasColumnType("smallint")
                        .HasColumnName("usu_tipdis");

                    b.Property<short?>("UsuTipfat")
                        .HasColumnType("smallint")
                        .HasColumnName("usu_tipfat");

                    b.HasKey("UsuNumppd");

                    b.ToTable("usu_t009ppd", "Database/Migration");
                });

            modelBuilder.Entity("BackendApi.Database.Entityes.T009PPI", b =>
                {
                    b.Property<long>("UsuNumppd")
                        .HasColumnType("bigint");

                    b.Property<short>("UsuSeqipd")
                        .HasColumnType("smallint");

                    b.Property<string>("UsuCodagc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("UsuCodemp")
                        .HasColumnType("smallint");

                    b.Property<string>("UsuCodfam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuCodpro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuDesnfv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuFinrec")
                        .HasColumnType("int");

                    b.Property<decimal?>("UsuPreuni")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UsuQtdped")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuUnimed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UsuVlrtot")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UsuNumppd", "UsuSeqipd");

                    b.ToTable("usu_t009ppi", "Database/Migration");
                });

            modelBuilder.Entity("BackendApi.Database.Entityes.T025PERF", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("usu_concstamp");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_nomeperf");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usu_normname");

                    b.HasKey("Id");

                    b.ToTable("usu_t025perf", "Database/Migration");
                });

            modelBuilder.Entity("BackendApi.Database.Entityes.T025USU", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("usu_t025usu", "Database/Migration");
                });
#pragma warning restore 612, 618
        }
    }
}
